version: '3.0'
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ruby_project_db
    ports: 
      - 5432:5432
    networks:
      - web_app
      
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/aplicacao
    depends_on:
      - database
    networks:
      - web_app

networks:
  web_app:
    driver: bridge