version: '3.0'
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: biblioteca_pessoal_development
    ports: 
      - 5432:5432

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rails db:migrate db:seed && rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/aplicacao
    depends_on:
      - database