version: '3.0'
services:
  database:
    container_name: database
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ruby_project_db
    ports: 
      - 5432:5432