# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.0.0'
      - name: Install dependencies
        run: |
            cd aplicacao/
            bundle install
      - name: Run tests
        run: |
            cd aplicacao/
            bundle exec rake

  lint:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        ruby-version: ['3.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
       # Change directory to aplication
      - name: Change directory to aplication
        run: cd aplicacao
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bundler-audit --update
      - name: Security audit application code
        run: brakeman -q -w2
      - name: Lint Ruby files
        run: rubocop --parallel
