# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: biblioteca_pessoal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.0.0'
      - name: Install dependencies
        run: |
            cd aplicacao/
            bundle install
      - name: Set up database schema
        run: |
            cd aplicacao/
            rails db:create
            rails db:migrate
            rails db:seed
      - name: Run tests
        run: |
            cd aplicacao/
            bundle exec rake

  lint:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        ruby-version: ['3.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          ruby-version: '3.0.0'
      # Add or replace any other lints here
      - name: Install Bundle
        run: |
          cd aplicacao/
          bundle install
      - name: Install Gems
        run: |
          gem install bundler-audit 
          gem install brakeman 
          gem install rubocop
      #- name: Security audit dependencies
      #  run: |
          # cd aplicacao/
          # bundler-audit --update
      # - name: Security audit application code
        # run: |
          # cd aplicacao/
          # brakeman -q -w2
      - name: Lint Ruby files
        run: |
          cd aplicacao/
          rubocop --parallel
